# Generated by Django 3.2.13 on 2022-05-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Enter first name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter last name', max_length=20, null=True)),
                ('patronymic', models.CharField(blank=True, help_text='Enter patronymic name', max_length=20, null=True)),
                ('classroom', models.CharField(blank=True, help_text='Enter classroom name', max_length=3, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='telegram name', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, help_text='telegram id', max_length=20, null=True)),
                ('username', models.CharField(blank=True, help_text='telegram name', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, help_text='Enter first name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter last name', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, help_text='vk id', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, help_text='Enter first name', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter last name', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('learner', models.BooleanField(default=False)),
                ('volunteer', models.BooleanField(default=False)),
                ('person', models.ForeignKey(help_text='Role person', null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.person')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message', max_length=20)),
                ('status', models.CharField(help_text='Status', max_length=20)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_creator', to='volunteers.person')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_owner', to='volunteers.person')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(help_text='Rating', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_creator', to='volunteers.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_owner', to='volunteers.person')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject', max_length=20)),
                ('theme', models.CharField(help_text='Theme', max_length=200)),
                ('status', models.CharField(default='Open', help_text='Status', max_length=20)),
                ('request_number', models.CharField(help_text='request_number', max_length=20)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_creator', to='volunteers.person')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_owner', to='volunteers.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Person_Telegram', to='volunteers.telegram'),
        ),
        migrations.AddField(
            model_name='person',
            name='vk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Person_VK', to='volunteers.vk'),
        ),
    ]
