# Generated by Django 3.2.13 on 2022-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requesthelp',
            name='creation_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
