# Generated by Django 3.2.13 on 2022-06-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20220617_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrating',
            name='request_number_help',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_number_help', to='volunteers.requesthelp'),
        ),
        migrations.AlterField(
            model_name='requesthelp',
            name='creation_date',
            field=models.DateField(auto_now=True, help_text='creation_date'),
        ),
        migrations.AlterField(
            model_name='requesthelp',
            name='creation_time',
            field=models.TimeField(auto_now=True, help_text='creation_time'),
        ),
    ]
