# Generated by Django 3.2.13 on 2022-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_auto_20220628_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='rating',
            field=models.CharField(help_text='rating', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='RequestRating',
        ),
    ]
