# Generated by Django 3.2.13 on 2022-09-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(help_text='Role person', null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.person', unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
